name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # or the version you prefer

      - name: Change to React App Directory
        run: cd my-react-website

      - name: Install Dependencies
        run: npm install
        working-directory: ./my-react-website

      - name: Build the App
        run: npm run build
        working-directory: ./my-react-website

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: deploywebsitetogithubpagesa  # ensure this is the correct branch
          folder: my-react-website/dist  # or the appropriate build output folder
