name: Deploy

on:
  push:
    branches:
      - 'main'  # or the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the node version compatible with your setup

      - name: Install Dependencies
        run: npm install
        working-directory: ./  # Root of the project

      - name: Build the App
        run: npm run build
        working-directory: ./  # Root of the project
      
      - name: List Output Files
        run: ls -l ./dist  # Ensure this matches where your build output is located

      - name: Deploy to Netlify
        run: npm install -g netlify-cli && netlify deploy --prod --dir=./dist --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
