name: CI Pipeline

on:
  push:
    branches:
      - 'main'  # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - 'main'  # Trigger on pull requests to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.13.1'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Install Deno
        run: |
          curl -fsSL https://deno.land/install.sh | sh
          echo 'export DENO_INSTALL="$HOME/.deno"' >> $GITHUB_ENV
          echo 'export PATH="$DENO_INSTALL/bin:$PATH"' >> $GITHUB_ENV

      - name: Run Tests
        run: npm test

      - name: Run Linter
        run: npm run lint

      - name: Build the App
        run: npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=./dist --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.13.1'

      - name: Install Dependencies
        run: npm install

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          languages: javascript

      - name: Run npm audit
        run: npm audit --audit-level=high
